// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.1; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ----------- //
// pulse_timer //
// ----------- //

#define pulse_timer_wrap_target 0
#define pulse_timer_wrap 14
#define pulse_timer_pio_version 0

static __pio_const uint16_t pulse_timer_program_instructions[] = {
            //     .wrap_target
    0xa02f, //  0: mov    x, ~osr
    0x00c8, //  1: jmp    pin, 8
    0x00c4, //  2: jmp    pin, 4
    0x0002, //  3: jmp    2
    0x00c6, //  4: jmp    pin, 6
    0x000c, //  5: jmp    12
    0x0044, //  6: jmp    x--, 4
    0x000c, //  7: jmp    12
    0x00c8, //  8: jmp    pin, 8
    0x000a, //  9: jmp    10
    0x00cc, // 10: jmp    pin, 12
    0x004a, // 11: jmp    x--, 10
    0xa049, // 12: mov    y, ~x
    0x4040, // 13: in     y, 32
    0x8000, // 14: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program pulse_timer_program = {
    .instructions = pulse_timer_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = pulse_timer_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pulse_timer_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pulse_timer_wrap_target, offset + pulse_timer_wrap);
    return c;
}

// initialize the PIO state machine
static inline void pulse_timer_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = pulse_timer_program_get_default_config(offset);
    // Map the physical sensor pin
    sm_config_set_jmp_pin(&c, pin);
    // Set the GPIO function matrix
    pio_gpio_init(pio, pin);
    gpio_pull_up(pin);
    // set input mode
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
    // Configure ISR
    // Shift left = false, Auto-push = false
    sm_config_set_in_shift(&c, false, false, 32);
    // join FIFO 
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    // Calculate the clock divider at 2 MHz
    float div = (float)clock_get_hz(clk_sys) / 2000000.f;
    sm_config_set_clkdiv(&c, div);
    // Load configurations
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

